### ISSUE TITLE
Implement APIs for LCP support

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/go-toolkit#22]
In order to support LCP, in addition to handling decryption, the streamer also needs to add two new interactions:

- a link to the LCP license
- an LCP license handler, to communicate User Key/Passphrase to the streamer

For the LCP license, the fetcher will serve directly `META-INF/license.lcpl` through a link at the publication level:
```json
{
  "href": "license.lcpl",
  "rel": "license",
  "type": "application/vnd.readium.lcp.license-1.0+json"
}
```

The LCP license handler will have the following interactions possible:

- Getting the handler document (GET)
- Sending the User Key/Passphrase (POST)

The following link is added to the publication's manifest:

```json
{
  "href": "license-handler.json",
  "rel": "http://readium.org/lcp/handler",
  "type": "application/json
}
```

The two interactions possible respond with the following documents:

```
GET license-handler.json
{
  "identifier": "62b2dfcb-48f0-4e1b-b2b0-8e3444960f13",
  "profile": "http://readium.org/lcp/basic-profile",
  "key": {
    "ready": false, 
    "check": "jJEjUDipHK3OjGt6kFq7dcOLZuicQFUYwQ+TYkAIWKm6Xv6kpHFhF7LOkUK/Owww"
  },
  "hint": {
    "text": "Enter your library card PIN",
    "url": "http://www.example.com/passphraseHint?user_id=1234"
  },
  "support": {
    "mail": "support@example.com",
    "url": "http://www.example.com/support",
    "tel": "1800836482"
  }
}
```

```
POST license-handler.json
{
  "key": {
    "hash": "9728be1c6737759dcba331ebe78276d8c83999b02d410aa2662c763915229a79"
  }
}
```

The `POST` request returns the full handler document, with the following HTTP status codes:
- 200 OK, when the key/passphrase is valid
- 401 Unauthorized, when the key/passphrase is invalid

**Comment by HadrienGardeur** [comment]
cc @llemeurfr @danielweck 

We're experimenting this first and based on our results we'll start a documentation and an epic to further discuss and specify on main repo.

**Comment by llemeurfr** [comment]
Question: it seems unsafe (from a personal info perspective) to post the passphrase in clear, even if we have allowed this in the open-source LCP server. Passing its hash (second example) seems better. 
-> Why providing the two solutions in r2? 
I copy @snemegeer and @danielweck because I forgot the rationale. 

Note: after you experiment, it would be great to have a sequence diagram describing how it works in the two cases a) the client gets the license and will decode the streams  b) the client posts the passphrase and expects the server to decode the streams.

**Comment by HadrienGardeur** [comment]
This is entirely meant for the use case where both the streamer and navigator are on the same client, not for server side LCP (which is still out of scope).

We've included both to make life easier for the launcher/navigator but it's definitely a point that should be up to discussions.

**Comment by HadrienGardeur** [comment]
TODO: Remove the option based on User Passphrase.

**Comment by HadrienGardeur** [comment]
Update: The first comment has been updated to remove the passphrase option.
