### ISSUE TITLE
HTTP Optimizations

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/go-toolkit#23]
In order to improve performance, a number of optimizations can also be handled at a HTTP level:

- manifest served with an ETag
- all resources from the publication served with `Cache-Control` header and a long expiration date

**Comment by HadrienGardeur** [comment]
While we initially planned on implementing rel="prerender" too, it's unclear if this would help apps at this point.
The results might be more convincing if the app is responsible for dynamically injecting rel="prerender" itself.

**Comment by banux** [comment]
Code in commit https://github.com/readium/r2-streamer-go/commit/b90c118151333b30f6249d69bbacab6db7860f15

**Comment by HadrienGardeur** [comment]
@chocolatkey I was about to close this outdated issue but it made me wonder what our current strategy is. Could you give me a quick summary here?

**Comment by chocolatkey** [comment]
Addressed for the most part in `rwp serve` command's web server.
