### ISSUE TITLE
EPUB version check

### ISSUE THREAD

**Issue by danielweck** [readium/go-toolkit#33]
https://github.com/readium/r2-streamer-go/blob/master/parser/epub.go#L202
```go
if epubVersion == "3.0" {
}
```

should be:
```go
if isEpub3OrMore(book) {
}
```

**Comment by danielweck** [comment]
Also in:
https://github.com/readium/r2-streamer-go/blob/master/parser/epub.go#L104
```go
	if epubVersion == epub3 {
```

**Comment by danielweck** [comment]
Note that `refines` is deprecated, not superseded:
http://www.idpf.org/epub/31/spec/epub-changes.html#sec-pkg-refines
http://www.idpf.org/epub/31/spec/epub-packages.html#attrdef-meta-refines
http://www.idpf.org/epub/31/spec/epub-spec.html#deprecated
"Reading Systems must continue to support the feature as it is defined until it is formally removed."

**Comment by banux** [comment]
Yes we can try to check it. I don't close the issue so we can tackle this later.
