### ISSUE TITLE
Media Overlays parsing: incorrect handling of body/seq epub:textref (IMO)

### ISSUE THREAD

**Issue by danielweck** [readium/go-toolkit#35]
In `fillMediaOverlay` ( https://github.com/readium/r2-streamer-go/blob/master/parser/epub.go#L695 ), `mo.Text = smil.Body.TextRef` can actually be undefined (such as Moby Dick's first two MO chapters https://github.com/IDPF/epub3-samples/blob/master/30/moby-dick-mo/OPS/chapter_001_overlay.smil#L2 ). The parsing algorithm in the recursive function `addSeqToMediaOverlay` ( https://github.com/readium/r2-streamer-go/blob/master/parser/epub.go#L737 ) attempts to "split" the Media Overlays based on the nested seqs' `epub:textref` values (see `baseHref == baseHrefParent` in the linked Go code), but this may actually results in skipped SMIL fragments and inconsistent JSON output.

I appreciate the optimisation effort (as we discussed during the Readium-2 conference calls, i.e. the edge case when single SMIL files reference multiple HTML documents), but in the NodeJS implementation I personally decided to replicate the Readium-1 parsing behaviour, which consists in parsing each individual SMIL file *in full*, and then attaching each resulting root Media Overlay to every HTML spine item that references said SMIL (i.e. OPF manifest items' `media-overlay` IDREF). In essence, I removed the special treatment of `mo.Text` (which is duplicated in both `fillMediaOverlay` and `addSeqToMediaOverlay`), and I added a single preliminary parsing step to construct the mapping: https://github.com/edrlab/r2-streamer-js/blob/develop/src/parser/epub.ts#L378-L421
This way, at worst there will be redundant Media Overlays timing data for a given HTML document (in the edge case where the SMIL file references multiple spine items), but in most cases the attached MO will contain exactly what an HTML document needs.

**Comment by danielweck** [comment]
Another way to put this:
I consider that the EPUB's OPF manifest items' `media-overlay` IDREF is the authoritative source of truth, rather than the `epub:textref` back-references embedded in each individual SMIL files. In other words, I trust the mapping directionality indicated in the OPF (HTML --> SMIL) rather than the other way around.

**Comment by HadrienGardeur** [comment]
I have mixed feelings about that:

- in general, the goal for Readium-2 is to make things easier for the app developer, if we simply follow the OPF, this means duplicating a lot of info and forcing people to filter the output of the media overlay API
- how do you create a response for the complete publication with your method? Do you store the original file name or id and deduplicate them?

**Comment by danielweck** [comment]
I believe the dominant production practice for EPUB3 Media Overlays is "1 HTML file <--> 1 SMIL file", just because it makes sense from an authoring point of view, as well as from a reading system perspective. Yes, in principle the specification allows a single SMIL file to reference multiple HTML documents, but in reality I believe that this is a rare edge-case (at least, based on my experience).
The "SMIL splitting" code in the Go "streamer" (well, "parser") is brittle because it relies on the assumptions made about `body/seq@epub:textref` (in fact, the reason why I chose to implement this differently in the JS parser is because some MO totally fail to load, because of missing `epub:textref`). Instead, the `manifest>item@media-overlay` attribute can (and should) be used reliably.

Note that the NodeJS implementation only differs from the Go one in that respect. The rest is identical (populating the JSON web pub manifest with a "fetcher" URL, and attaching the constructed Media Overlay structures to the internal data model).

**Comment by HadrienGardeur** [comment]
We initially implemented EPUB Media Overlays like you did in Javascript, but when we realized that a single SMIL file could reference multiple spine items, we took another direction.

If you request to the streamer the media overlay per spine item, it's not ideal in your scenario (need to filter the nodes based on the spine item being referenced) but it could be worse.
But when you do a request for the whole publication, it looks IMO really bad.

Let me give you an example:

- let's say that we have three chapters (Chapter 1, Chapter 2, Chapter 3)
- and a single SMIL that contains media overlays for all three chapters

If we simply follow `manifest>item@media-overlay` we'll duplicate the info three times, but that's not the worst part.
When a navigator sends a request for the complete media overlays (all spine items) it'll see:
- Chapter 1
- Chapter 2
- Chapter 3
- Chapter 1
- Chapter 2
- Chapter 3
- Chapter 1
- Chapter 2
- Chapter 3

No matter how we filter and deduplicate, I feel very strongly that we should absolutely do it at a streamer level.

We've decided to filter at a parser level, and there might be edge cases that we've missed. 

But I'd much rather deal with those edge cases, document them, fix them and have tests to cover them, than avoid this situation and let the app developers have to deal with it.
