### ISSUE TITLE
Images are missing `height` `width`

### ISSUE THREAD

**Issue by jccr** [readium/go-toolkit#50]
I noticed this change when comparing outputs of the Go streamer and the JS streamer.
![Screen Shot 2020-03-18 at 6 15 22 AM](https://user-images.githubusercontent.com/5132652/76964472-08556a80-68e0-11ea-9158-c7d1397de892.png)

**Comment by HadrienGardeur** [comment]
There's a cost in doing that though. If we add this as a feature, we need to make sure that it can be turned off as well.

**Comment by danielweck** [comment]
I have not measured the runtime costs empirically, but there sure is an impact when parsing (for example) an EPUB, and when every image resource is accessed to determine the width + height. In the Node / JavaScript implementation (TypeScript) this job is blocking (waiting on an async promise), and the job is delegated to an external library that knows how to parse image file headers. The filesystem I/O is minimal in terms of the number of bytes accessed, but opening/closing many file handles is not completely free :)

**Comment by jccr** [comment]
Ah yes.. I remember that blocking job very well :)
Thanks, both of you, for the reminder about the cost of calculating this.
