### ISSUE TITLE
Re-add comicrack metadata support in CBZ

### ISSUE THREAD

**Issue by chocolatkey** [readium/go-toolkit#62]

**Comment by HadrienGardeur** [comment]
@chocolatkey this could also remain a draft and pushed to the icebox once properly documented

**Comment by chocolatkey** [comment]
@HadrienGardeur I closed this PR because it's covered in the more PR regarding comic metadata I'd like to work on fairly soon. Do you think this one should be separate?

**Comment by HadrienGardeur** [comment]
No, that's fine in that case, as long as we explicitly mention Comicrack in the other issue.
